
# Configuração padrão

name: Bug Report
description: File a bug report.
title: "TITULO AQUI"

# As pessoas que serão automaticamente atribuídas a problemas criados com este modelo.
assignees:

# Etiquetas que serão adicionadas automaticamente a problemas criados com este modelo.
labels: ["Obrigatório"]


